// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MincoTraj.proto

#include "MincoTraj.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_SingleMinco_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SingleMinco_SingleMinco_2eproto;
namespace apollo {
namespace shenlan {
namespace mpc {
class MincoTrajDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MincoTraj> _instance;
} _MincoTraj_default_instance_;
}  // namespace mpc
}  // namespace shenlan
}  // namespace apollo
static void InitDefaultsscc_info_MincoTraj_MincoTraj_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::shenlan::mpc::_MincoTraj_default_instance_;
    new (ptr) ::apollo::shenlan::mpc::MincoTraj();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::shenlan::mpc::MincoTraj::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MincoTraj_MincoTraj_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MincoTraj_MincoTraj_2eproto}, {
      &scc_info_SingleMinco_SingleMinco_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_MincoTraj_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_MincoTraj_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_MincoTraj_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_MincoTraj_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::MincoTraj, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::MincoTraj, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::MincoTraj, trajs_),
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::apollo::shenlan::mpc::MincoTraj)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::apollo::shenlan::mpc::_MincoTraj_default_instance_),
};

const char descriptor_table_protodef_MincoTraj_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017MincoTraj.proto\022\022apollo.shenlan.mpc\032\021S"
  "ingleMinco.proto\";\n\tMincoTraj\022.\n\005trajs\030\001"
  " \003(\0132\037.apollo.shenlan.mpc.SingleMinco"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_MincoTraj_2eproto_deps[1] = {
  &::descriptor_table_SingleMinco_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_MincoTraj_2eproto_sccs[1] = {
  &scc_info_MincoTraj_MincoTraj_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_MincoTraj_2eproto_once;
static bool descriptor_table_MincoTraj_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MincoTraj_2eproto = {
  &descriptor_table_MincoTraj_2eproto_initialized, descriptor_table_protodef_MincoTraj_2eproto, "MincoTraj.proto", 117,
  &descriptor_table_MincoTraj_2eproto_once, descriptor_table_MincoTraj_2eproto_sccs, descriptor_table_MincoTraj_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_MincoTraj_2eproto::offsets,
  file_level_metadata_MincoTraj_2eproto, 1, file_level_enum_descriptors_MincoTraj_2eproto, file_level_service_descriptors_MincoTraj_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MincoTraj_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_MincoTraj_2eproto), true);
namespace apollo {
namespace shenlan {
namespace mpc {

// ===================================================================

void MincoTraj::InitAsDefaultInstance() {
}
class MincoTraj::_Internal {
 public:
  using HasBits = decltype(std::declval<MincoTraj>()._has_bits_);
};

void MincoTraj::clear_trajs() {
  trajs_.Clear();
}
MincoTraj::MincoTraj()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.shenlan.mpc.MincoTraj)
}
MincoTraj::MincoTraj(const MincoTraj& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      trajs_(from.trajs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.shenlan.mpc.MincoTraj)
}

void MincoTraj::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MincoTraj_MincoTraj_2eproto.base);
}

MincoTraj::~MincoTraj() {
  // @@protoc_insertion_point(destructor:apollo.shenlan.mpc.MincoTraj)
  SharedDtor();
}

void MincoTraj::SharedDtor() {
}

void MincoTraj::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MincoTraj& MincoTraj::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MincoTraj_MincoTraj_2eproto.base);
  return *internal_default_instance();
}


void MincoTraj::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.shenlan.mpc.MincoTraj)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  trajs_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* MincoTraj::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .apollo.shenlan.mpc.SingleMinco trajs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_trajs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MincoTraj::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.shenlan.mpc.MincoTraj)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.shenlan.mpc.SingleMinco trajs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_trajs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(1, this->_internal_trajs(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.shenlan.mpc.MincoTraj)
  return target;
}

size_t MincoTraj::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.shenlan.mpc.MincoTraj)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .apollo.shenlan.mpc.SingleMinco trajs = 1;
  total_size += 1UL * this->_internal_trajs_size();
  for (const auto& msg : this->trajs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MincoTraj::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.shenlan.mpc.MincoTraj)
  GOOGLE_DCHECK_NE(&from, this);
  const MincoTraj* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MincoTraj>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.shenlan.mpc.MincoTraj)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.shenlan.mpc.MincoTraj)
    MergeFrom(*source);
  }
}

void MincoTraj::MergeFrom(const MincoTraj& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.shenlan.mpc.MincoTraj)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  trajs_.MergeFrom(from.trajs_);
}

void MincoTraj::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.shenlan.mpc.MincoTraj)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MincoTraj::CopyFrom(const MincoTraj& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.shenlan.mpc.MincoTraj)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MincoTraj::IsInitialized() const {
  return true;
}

void MincoTraj::InternalSwap(MincoTraj* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  trajs_.InternalSwap(&other->trajs_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MincoTraj::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mpc
}  // namespace shenlan
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::apollo::shenlan::mpc::MincoTraj* Arena::CreateMaybeMessage< ::apollo::shenlan::mpc::MincoTraj >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::shenlan::mpc::MincoTraj >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
