// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EgoVehicleStatus.proto

#include "EgoVehicleStatus.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_header_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Header_header_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_pose_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_Pose_pose_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_EgoVehicleControl_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_EgoVehicleControl_EgoVehicleControl_2eproto;
namespace apollo {
namespace shenlan {
namespace mpc {
class EgoVehicleStatusDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EgoVehicleStatus> _instance;
} _EgoVehicleStatus_default_instance_;
}  // namespace mpc
}  // namespace shenlan
}  // namespace apollo
static void InitDefaultsscc_info_EgoVehicleStatus_EgoVehicleStatus_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::shenlan::mpc::_EgoVehicleStatus_default_instance_;
    new (ptr) ::apollo::shenlan::mpc::EgoVehicleStatus();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::shenlan::mpc::EgoVehicleStatus::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_EgoVehicleStatus_EgoVehicleStatus_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_EgoVehicleStatus_EgoVehicleStatus_2eproto}, {
      &scc_info_Header_header_2eproto.base,
      &scc_info_Pose_pose_2eproto.base,
      &scc_info_EgoVehicleControl_EgoVehicleControl_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_EgoVehicleStatus_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_EgoVehicleStatus_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_EgoVehicleStatus_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_EgoVehicleStatus_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, header_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, pose_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, velocity_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, acceleration_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, curvature_),
  PROTOBUF_FIELD_OFFSET(::apollo::shenlan::mpc::EgoVehicleStatus, control_),
  0,
  1,
  3,
  4,
  5,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::apollo::shenlan::mpc::EgoVehicleStatus)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::apollo::shenlan::mpc::_EgoVehicleStatus_default_instance_),
};

const char descriptor_table_protodef_EgoVehicleStatus_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026EgoVehicleStatus.proto\022\022apollo.shenlan"
  ".mpc\032\014header.proto\032\027EgoVehicleControl.pr"
  "oto\032\npose.proto\"\325\001\n\020EgoVehicleStatus\022%\n\006"
  "header\030\001 \001(\0132\025.apollo.common.Header\022\'\n\004P"
  "ose\030\002 \001(\0132\031.apollo.localization.Pose\022\020\n\010"
  "velocity\030\003 \001(\002\022\024\n\014acceleration\030\004 \001(\002\022\021\n\t"
  "curvature\030\005 \001(\002\0226\n\007control\030\006 \001(\0132%.apoll"
  "o.shenlan.mpc.EgoVehicleControl"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_EgoVehicleStatus_2eproto_deps[3] = {
  &::descriptor_table_EgoVehicleControl_2eproto,
  &::descriptor_table_header_2eproto,
  &::descriptor_table_pose_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_EgoVehicleStatus_2eproto_sccs[1] = {
  &scc_info_EgoVehicleStatus_EgoVehicleStatus_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_EgoVehicleStatus_2eproto_once;
static bool descriptor_table_EgoVehicleStatus_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_EgoVehicleStatus_2eproto = {
  &descriptor_table_EgoVehicleStatus_2eproto_initialized, descriptor_table_protodef_EgoVehicleStatus_2eproto, "EgoVehicleStatus.proto", 311,
  &descriptor_table_EgoVehicleStatus_2eproto_once, descriptor_table_EgoVehicleStatus_2eproto_sccs, descriptor_table_EgoVehicleStatus_2eproto_deps, 1, 3,
  schemas, file_default_instances, TableStruct_EgoVehicleStatus_2eproto::offsets,
  file_level_metadata_EgoVehicleStatus_2eproto, 1, file_level_enum_descriptors_EgoVehicleStatus_2eproto, file_level_service_descriptors_EgoVehicleStatus_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_EgoVehicleStatus_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_EgoVehicleStatus_2eproto), true);
namespace apollo {
namespace shenlan {
namespace mpc {

// ===================================================================

void EgoVehicleStatus::InitAsDefaultInstance() {
  ::apollo::shenlan::mpc::_EgoVehicleStatus_default_instance_._instance.get_mutable()->header_ = const_cast< ::apollo::common::Header*>(
      ::apollo::common::Header::internal_default_instance());
  ::apollo::shenlan::mpc::_EgoVehicleStatus_default_instance_._instance.get_mutable()->pose_ = const_cast< ::apollo::localization::Pose*>(
      ::apollo::localization::Pose::internal_default_instance());
  ::apollo::shenlan::mpc::_EgoVehicleStatus_default_instance_._instance.get_mutable()->control_ = const_cast< ::apollo::shenlan::mpc::EgoVehicleControl*>(
      ::apollo::shenlan::mpc::EgoVehicleControl::internal_default_instance());
}
class EgoVehicleStatus::_Internal {
 public:
  using HasBits = decltype(std::declval<EgoVehicleStatus>()._has_bits_);
  static const ::apollo::common::Header& header(const EgoVehicleStatus* msg);
  static void set_has_header(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::apollo::localization::Pose& pose(const EgoVehicleStatus* msg);
  static void set_has_pose(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_velocity(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_acceleration(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_curvature(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static const ::apollo::shenlan::mpc::EgoVehicleControl& control(const EgoVehicleStatus* msg);
  static void set_has_control(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::apollo::common::Header&
EgoVehicleStatus::_Internal::header(const EgoVehicleStatus* msg) {
  return *msg->header_;
}
const ::apollo::localization::Pose&
EgoVehicleStatus::_Internal::pose(const EgoVehicleStatus* msg) {
  return *msg->pose_;
}
const ::apollo::shenlan::mpc::EgoVehicleControl&
EgoVehicleStatus::_Internal::control(const EgoVehicleStatus* msg) {
  return *msg->control_;
}
void EgoVehicleStatus::clear_header() {
  if (header_ != nullptr) header_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void EgoVehicleStatus::clear_pose() {
  if (pose_ != nullptr) pose_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void EgoVehicleStatus::clear_control() {
  if (control_ != nullptr) control_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
EgoVehicleStatus::EgoVehicleStatus()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.shenlan.mpc.EgoVehicleStatus)
}
EgoVehicleStatus::EgoVehicleStatus(const EgoVehicleStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_header()) {
    header_ = new ::apollo::common::Header(*from.header_);
  } else {
    header_ = nullptr;
  }
  if (from._internal_has_pose()) {
    pose_ = new ::apollo::localization::Pose(*from.pose_);
  } else {
    pose_ = nullptr;
  }
  if (from._internal_has_control()) {
    control_ = new ::apollo::shenlan::mpc::EgoVehicleControl(*from.control_);
  } else {
    control_ = nullptr;
  }
  ::memcpy(&velocity_, &from.velocity_,
    static_cast<size_t>(reinterpret_cast<char*>(&curvature_) -
    reinterpret_cast<char*>(&velocity_)) + sizeof(curvature_));
  // @@protoc_insertion_point(copy_constructor:apollo.shenlan.mpc.EgoVehicleStatus)
}

void EgoVehicleStatus::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EgoVehicleStatus_EgoVehicleStatus_2eproto.base);
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&curvature_) -
      reinterpret_cast<char*>(&header_)) + sizeof(curvature_));
}

EgoVehicleStatus::~EgoVehicleStatus() {
  // @@protoc_insertion_point(destructor:apollo.shenlan.mpc.EgoVehicleStatus)
  SharedDtor();
}

void EgoVehicleStatus::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete pose_;
  if (this != internal_default_instance()) delete control_;
}

void EgoVehicleStatus::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EgoVehicleStatus& EgoVehicleStatus::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EgoVehicleStatus_EgoVehicleStatus_2eproto.base);
  return *internal_default_instance();
}


void EgoVehicleStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.shenlan.mpc.EgoVehicleStatus)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(header_ != nullptr);
      header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(pose_ != nullptr);
      pose_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(control_ != nullptr);
      control_->Clear();
    }
  }
  if (cached_has_bits & 0x00000038u) {
    ::memset(&velocity_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&curvature_) -
        reinterpret_cast<char*>(&velocity_)) + sizeof(curvature_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* EgoVehicleStatus::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .apollo.common.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .apollo.localization.Pose Pose = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_pose(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional float velocity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          _Internal::set_has_velocity(&has_bits);
          velocity_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional float acceleration = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          _Internal::set_has_acceleration(&has_bits);
          acceleration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional float curvature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          _Internal::set_has_curvature(&has_bits);
          curvature_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional .apollo.shenlan.mpc.EgoVehicleControl control = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_control(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EgoVehicleStatus::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.shenlan.mpc.EgoVehicleStatus)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.common.Header header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::header(this), target, stream);
  }

  // optional .apollo.localization.Pose Pose = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, _Internal::pose(this), target, stream);
  }

  // optional float velocity = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_velocity(), target);
  }

  // optional float acceleration = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_acceleration(), target);
  }

  // optional float curvature = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_curvature(), target);
  }

  // optional .apollo.shenlan.mpc.EgoVehicleControl control = 6;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, _Internal::control(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.shenlan.mpc.EgoVehicleStatus)
  return target;
}

size_t EgoVehicleStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.shenlan.mpc.EgoVehicleStatus)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional .apollo.common.Header header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *header_);
    }

    // optional .apollo.localization.Pose Pose = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *pose_);
    }

    // optional .apollo.shenlan.mpc.EgoVehicleControl control = 6;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *control_);
    }

    // optional float velocity = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 4;
    }

    // optional float acceleration = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

    // optional float curvature = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 4;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoVehicleStatus::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.shenlan.mpc.EgoVehicleStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoVehicleStatus* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EgoVehicleStatus>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.shenlan.mpc.EgoVehicleStatus)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.shenlan.mpc.EgoVehicleStatus)
    MergeFrom(*source);
  }
}

void EgoVehicleStatus::MergeFrom(const EgoVehicleStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.shenlan.mpc.EgoVehicleStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_header()->::apollo::common::Header::MergeFrom(from._internal_header());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_pose()->::apollo::localization::Pose::MergeFrom(from._internal_pose());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_control()->::apollo::shenlan::mpc::EgoVehicleControl::MergeFrom(from._internal_control());
    }
    if (cached_has_bits & 0x00000008u) {
      velocity_ = from.velocity_;
    }
    if (cached_has_bits & 0x00000010u) {
      acceleration_ = from.acceleration_;
    }
    if (cached_has_bits & 0x00000020u) {
      curvature_ = from.curvature_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void EgoVehicleStatus::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.shenlan.mpc.EgoVehicleStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoVehicleStatus::CopyFrom(const EgoVehicleStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.shenlan.mpc.EgoVehicleStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoVehicleStatus::IsInitialized() const {
  return true;
}

void EgoVehicleStatus::InternalSwap(EgoVehicleStatus* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(header_, other->header_);
  swap(pose_, other->pose_);
  swap(control_, other->control_);
  swap(velocity_, other->velocity_);
  swap(acceleration_, other->acceleration_);
  swap(curvature_, other->curvature_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EgoVehicleStatus::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mpc
}  // namespace shenlan
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::apollo::shenlan::mpc::EgoVehicleStatus* Arena::CreateMaybeMessage< ::apollo::shenlan::mpc::EgoVehicleStatus >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::shenlan::mpc::EgoVehicleStatus >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
